Trunk/tpco_amway_spop/CargaArchivo/Controllers/CargaController.cs
using BLL;
using CargaArchivo.Models;
using CargaArchivo.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CargaArchivo.Controllers
{
    public class CargaController : Controller
    {
        public string UserInfo = null;
        public ActionResult Index(string usuario)
        {
            if (!string.IsNullOrEmpty(usuario))
            {
                Services.clsUtils.strUser = usuario;
            }
            //return RedirectToAction("Home", "Index");

            return View("Index");
        }

        [HttpPost]
        public ActionResult LoadFile(HttpPostedFileBase postedFile)
        {
            try
            {
                string path = Server.MapPath(clsGlobal.DirUpload);
                string filepath = string.Empty;
                if (postedFile != null)
                {
                    if (string.IsNullOrEmpty(Services.clsUtils.strUser))
                    {
                        return Json(new { Value = false, Message = "No se ha especificado un usuario para la aplicación" }, JsonRequestBehavior.AllowGet);
                    }


                    clsGlobal.Log.RegisterEvent(FEventType.Info, "Paso la ejecución del usuario ", null, null, Environment.UserName);

                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    filepath = path + Path.GetFileName(postedFile.FileName);
                    int index = filepath.IndexOf(".xlsx");
                    filepath = filepath.Substring(0, index);
                    filepath = filepath + DateTime.Now.ToString("yyyy_MM_dd_mm_ss") + ".xlsx";

                    postedFile.SaveAs(System.IO.Path.Combine(filepath));

                    DataLoadInfo LoadFile = new DataLoadInfo();
                    if (LoadFile.ValidarParametros(postedFile, out string msg) == false)
                    {
                        return Json(new { Value = false, Message = msg }, JsonRequestBehavior.AllowGet);
                    }

                    clsGlobal.Log.RegisterEvent(FEventType.Info, "Pasó el validar parametros ", null, null, Environment.UserName);

                    DataTable xlsWBIPS = clsReadExcelFile.GetDataFromExcel(filepath, 1);

                    clsGlobal.Log.RegisterEvent(FEventType.Info, "leyó el excel ", null, null, Environment.UserName);

                    if (xlsWBIPS.Rows.Count <= 0)
                    {
                        return Json(new { Value = false, Message = "No se proceso correctamente el archivo" }, JsonRequestBehavior.AllowGet);
                    }

                    //Validamos que sea una fecha valida
                    if (LoadFile.ValidarFechaCorrectaIngresada(xlsWBIPS, out string Msg) == false)
                    {
                        return Json(new { Value = false, Message = Msg }, JsonRequestBehavior.AllowGet);
                    }

                    //Adicionamos los dias de antiguedad
                   // LoadFile.AdicionarDias(xlsWBIPS);

                    //Insertamos los datos temporales
                    LoadFile.InsertarDatosTemporales(xlsWBIPS, Services.clsUtils.strUser, out string message);
                    if (message != "")
                    {
                        return Json(new { Value = false, Message = message }, JsonRequestBehavior.AllowGet);
                    }


                    //Validamos los datos insertados,si esta configurado que si
                    if (clsGlobal.ValidarDatos == "SI")
                    {
                        string Validacion = LoadFile.ValidarDatosInsertados();
                        if (Validacion != string.Empty)
                        {
                            return Json(new { Value = false, Message = Validacion }, JsonRequestBehavior.AllowGet);
                        }
                        clsGlobal.Log.RegisterEvent(FEventType.Info, "Validó los datos", null, null, Environment.UserName);
                    }

                   
                                      


                    LoadFile.InsertarDatos(xlsWBIPS, Services.clsUtils.strUser, out string mensaje);
                    if (mensaje!="")
                    {
                        clsGlobal.Log.RegisterEvent(FEventType.Info, "Error insertando los datos", null, null, Environment.UserName);
                        return Json(new { Value = false, Message = mensaje }, JsonRequestBehavior.AllowGet);
                    }

                    clsGlobal.Log.RegisterEvent(FEventType.Info, "Insertó los registros ", null, null, Environment.UserName);

                    postedFile.InputStream.Dispose();


                }

            }
            catch (Exception ex)
            {
                return Json(new { Value = false, Message = "Error: " + ex.Message }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Value = true, Message = "Datos insertados correctamente" }, JsonRequestBehavior.AllowGet);

        }

        // GET: Carga/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Carga/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Carga/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Carga/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Carga/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Carga/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Carga/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Trunk/tpco_amway_spop/CargaArchivo/Views/Carga/Index.cshtml
@{
    ViewBag.Title = "Load File";
}

<div class="row">
    @using (Html.BeginForm())

    {
        @*<input type="file" id="fileUpload" name="postdFile" />
            <input type="submit"  id="btn-load-ajax" value="Import" />*@


        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="mb-3 mt-3">
                        <h2 class="mb-3" style="font-weight:300"> Cargar archivo</h2>
                        <div class="form-group mb-3">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="file_input" oninput="input_filename();">
                                <label for="file_input" id="file_input_label" class="custom-file-label"> Seleccionar archivo</label>

                            </div>
                        </div>


                        <button onclick="upload('{{request.url}}')" id="upload_btn" type="button" class="btn btn-primary">Importar archivo </button>
                        <button class="btn btn-primary d-none" id="loading_btn" type="button" disabled>
                            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                            Cargando...
                        </button>
                        <button class="btn btn-secondary d-none" id="cancel_btn" type="button"> Cancelar</button>
                    </div>
                    <div id="progress_wrapper" class="d-none">
                        <label id="progress_status">50% Cargado</label>
                        <div class="progress mb-3">
                            <div id="progress" class="progress-bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                            </div>
                        </div>
                    </div>
                    <div id="alert_wrapper"></div>
                    <div id="divLoad">
                        <button type="button"
                                class="button">
                            <span class="button__text"> Save Changes</span>
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <input type="hidden" class="btn btn-info btn-lg" data-toggle="modal" data-target="#ModalMessages" id="modalmessages" />
        <div id="ModalMessages" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <!-- Contenido del modal -->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div id="message" class="TitleTable" style="font-size:120%; align-content:center"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="DateSell btn btn-outline create_c" style="font-family:Calibri Light; font-size:15px; color: #ffffff !important " data-dismiss="modal" id="t" onclick="Recharge()">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

<style>
    .button {
        position: relative;
        padding: 0px 0px 16px;
        background: #CCE5FF;
        border: none;
        outline: none;
        border-radius: 2px;
        cursor: pointer;
        width: 300px;
        height: 50px;
    }

        .button:active {
            background: #CCE5FF;
        }

    .button__text {
        font: bold 20px 'Quicksand', san-serif;
        color: #ffffff;
        transition: all 0.2s;
    }

    .button--loading .button__text {
        visibility: hidden;
        opacity: 0;
    }

    .button--loading::after {
        content: "";
        position: absolute;
        width: 40px;
        height: 40px;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        margin: auto;
        border: 5px solid transparent;
        border-top-color: #ffffff;
        border-radius: 80%;
        animation: button-loading-spinner 1s ease infinite;
    }

    @@keyframes button-loading-spinner {
        from {
            transform: rotate(0turn);
        }

        to {
            transform: rotate(1turn);
        }
    }
</style>

@section Scripts
{
    <script>

        var progressFile = document.getElementById("progressBardiv");
        var progress = document.getElementById("progress");
        var progress_wrapper = document.getElementById("progress_wrapper");
        var progress_status = document.getElementById("progress_status");

        var upload_btn = document.getElementById("upload_btn");
        var loading_btn = document.getElementById("loading_btn");
        var cancel_btn = document.getElementById("cancel_btn");


        var alert_wrapper = document.getElementById("alert_wrapper");
        var input = document.getElementById("file_input");
        var file_input_label = document.getElementById("file_input_label");
        const btn = document.querySelector(".button");


        function show_alert(message, alert) {
            alert_wrapper.innerHTML = `
                <div id="box" class="alert alert-${alert} alert-dismissible fade show" role="alert">
                  <span>${message}</span>
                  <button type="button" onclick="document.getElementById('box').style.display='none';" class="close" data-dismiss="alert" aria-label="Close" >
                                <span aria-hidden="true">&times;</span>
                  </button >
                </div >`;

        };

        function input_filename() {
            file_input_label.innerText = input.files[0].name;
        };

        function upload(url) {
            //console.log(url.file);
            //console.log(input.files[0].name);


            var selectedFile = ($('#file_input'))[0].files[0];

            if (!selectedFile) {
                show_alert("No hay archivo seleccionado", "warning");
                return;
            }

            //if (!input.files[0].name)
            //{
            //    show_alert("No hay archivo seleccionado", "warning");
            //    return;
            //}

            var data = new FormData();
            var request = new XMLHttpRequest();
            request.responseType = "json";
            alert_wrapper.innerHTML = "";
            input.disabled = true;

           // upload_btn.classList.add("d-none");
            loading_btn.classList.remove("d-none");
            cancel_btn.classList.remove("d-none");

            progress_wrapper.classList.remove("d-none");

            var file = input.files[0];
            var filename = file.name;
            var filesize = file.size;
            document.cookie = `filesize=${filesize}`;

            data.append("file", file);

            request.upload.addEventListener("progress", function (e) {
                console.log("progress");
                var loaded = e.loaded;
                var total = e.total;
                var porcentage_completed = (loaded / total) * 100;
                progress.setAttribute("style", `width:${Math.floor(porcentage_completed)}%`);
                progress_status.innerText = `${Math.floor(porcentage_completed)}% Cargado`;


            })

            request.addEventListener("load", function (e) {
                console.log("load");
                console.log(request.status);
                console.log(request.response);
                if (request.status == 200) {
                    show_alert("Archivo cargado", "success")

                }
                else
                {
                    show_alert(`Error en la carga requerido`, "danger");
                }
                reset();
                loadFileToServer();
            })

            request.addEventListener("abort", function (e) {
                console.log("abort");
                reset();
                show_alert("Carga cancelada", "primary");
            })

            request.addEventListener("error", function (e) {
                console.log("error");
                reset();
                show_alert("Error en la carga", "danger");
            })



            //request.open("POST", "/TPCLCODESAGrupoSura/CargaEPP/", true)
            request.open("POST", "/Carga/", true)
            //request.open("POST", url);
            console.log(data);


            cancel_btn.addEventListener("click", function () {
                console.log("cancel");
                request.abort();
            })

            function reset() {
                console.log("reset");
                input.Value = null;
                input.disabled = false;
                cancel_btn.classList.add("d-none");
                loading_btn.classList.add("d-none");
               // upload_btn.classList.add("d-none");
                progress_wrapper.classList.add("d-none");
                progress.setAttribute("style", "width: 0%");

                //file_input_label.innerText = "Archivo seleccionado"
            }

            function loadFileToServer()
            {
                console.log("loadFileToServer");
                show_alert("Procesando el archvo", "primary");
                document.getElementById('divLoad').style.display = 'block';
                btn.classList.add("button--loading");
                var selectedFile = ($('#file_input'))[0].files[0];
                var datastring = new FormData();
                datastring.append("postedFile", selectedFile);
                console.log(datastring);
                $.ajax({
                    url: '@Url.Action("LoadFile", "Carga")',
                    type: "POST",
                    data: datastring,
                    contentType: false,
                    processData: false,
                    success: function (data)
                    {

                        if (typeof (data.Value) == "true")
                        {
                            show_alert("Archivo procesado", "success");
                            $("#message").html("");
                            $('#message').append(data.Message);
                            $('#modalmessages').click();
                            btn.classList.remove("button--loading");
                            document.getElementById('divLoad').style.display = 'none';

                        }
                        else
                        {
                            alert_wrapper.innerHTML = "";
                            $("#message").html("");
                            $('#message').append(data.Message);
                            $('#modalmessages').click();
                            btn.classList.remove("button--loading");
                            document.getElementById('divLoad').style.display = 'none';
                        }
                    }

                });

            }

            request.send(data);


        }//end upload



        $(document).ready(function () {

            document.getElementById('divLoad').style.display = 'none';

             $('#btn-load-ajax').click(function ()
            {
                console.log("ajax");
                var selectedFile = ($('#fileUpload'))[0].files[0];
                var datastring = new FormData();
                datastring.append("postedFile", selectedFile);
                if (!selectedFile) {
                    alert("No se ha cargado algun archivo");
                }

                $.ajax({
                    url: '@Url.Action("LoadFile", "Carga")',
                    type: "POST",
                    data: datastring,
                    contentType: false,
                    processData: false,
                    success: function (data)
                    {

                        if (typeof (data.Value) != "undefined") {
                            alert(data.Message);
                        }
                        else
                        {
                            alert("error no controlado");
                        }
                    }

                });


            });
        });
    </script>
}